### ISSUE TITLE
pi.hole/admin黑屏且点不进去是怎么回事？

### ISSUE THREAD

**Issue by Jim78778** [jacyl4/de_GWD#1]
还有添加节点，黑白名单，有弹窗提示却无法保存

**Comment by jacyl4** [comment]
> 还有添加节点，黑白名单，有弹窗提示却无法保存

彻底重新安装

**Comment by Jim78778** [comment]
你更新之后出事了
Cloning into 'dns-over-https'...
fatal: unable to access 'https://github.com/m13253/dns-over-https.git/': Could not resolve host: github.com
./client: line 245: cd: dns-over-https: No such file or directory
make: *** No targets specified and no makefile found.  Stop.
/etc/dns-over-https/doh-client.conf: No such file or directory
sed: can't read /etc/dns-over-https/doh-client.conf: No such file or directory
sed: can't read /etc/dns-over-https/doh-client.conf: No such file or directory
sed: can't read /etc/dns-over-https/doh-client.conf: No such file or directory
sed: can't read /etc/dns-over-https/doh-client.conf: No such file or directory
Failed to restart doh-client.service: Unit doh-client.service not found.
Failed to enable unit: File doh-client.service: No such file or directory
稍稍等待。。。

**Comment by jacyl4** [comment]
明显是dns不对啊。重装的时候，不把上级路由的dhcp恢复的么？

> 你更新之后出事了
> Cloning into 'dns-over-https'...
> fatal: unable to access 'https://github.com/m13253/dns-over-https.git/': Could not resolve host: github.com
> ./client: line 245: cd: dns-over-https: No such file or directory
> make: *** No targets specified and no makefile found. Stop.
> /etc/dns-over-https/doh-client.conf: No such file or directory
> sed: can't read /etc/dns-over-https/doh-client.conf: No such file or directory
> sed: can't read /etc/dns-over-https/doh-client.conf: No such file or directory
> sed: can't read /etc/dns-over-https/doh-client.conf: No such file or directory
> sed: can't read /etc/dns-over-https/doh-client.conf: No such file or directory
> Failed to restart doh-client.service: Unit doh-client.service not found.
> Failed to enable unit: File doh-client.service: No such file or directory
> 稍稍等待。。。

明显是dns不对啊。重装的时候，不把上级路由的dhcp恢复的么？

**Comment by jacyl4** [comment]
普通的路由连接问题，到电报群交流吧。
